### ISSUE TITLE
error simulating spectrum

### ISSUE THREAD

**Issue by alessandropeca** [XRStools/soxs#7]
I got the following error:
` astropy.units.core.UnitConversionError: 'ph / (keV s)' and 'ph / (arcmin2 keV s)' are not convertible`

when I try to simulate a spectrum, like as explained in the documentation:
`simulate_spectrum(spec, instrument, exp_time, out_file, ptsrc_bkgnd=True, foreground=True,
                  instr_bkgnd=True, overwrite=True, bkgnd_area=(0.5, "arcmin**2"))`
where I am wrong?

**Comment by jzuhone** [comment]
hi @alessandropeca, 

What is the Python version, Numpy version, and SOXS version you are using?

**Comment by jzuhone** [comment]
@alessandropeca never mind, I can reproduce this bug. Fixing now...

**Comment by jzuhone** [comment]
@alessandropeca, I've fixed this. You can get it by either downloading SOXS from source using GitHub and installing it or I will try to get a new release out by tonight.

**Comment by alessandropeca** [comment]
thanks @jzuhone ,  now it's working!
